# Generated by Django 5.2.3 on 2025-07-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0003_mailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['id'], 'verbose_name': 'mailing', 'verbose_name_plural': 'mailings'},
        ),
    ]
