# Generated by Django 5.2.3 on 2025-07-05 11:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0004_alter_mailing_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attemp_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Успешно', 'Успешно'), ('Не успешно', 'Не успешно')], max_length=10)),
                ('server_response', models.TextField()),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_attempts', to='mailing_service.mailing')),
            ],
            options={
                'verbose_name': 'send_attemp',
                'verbose_name_plural': 'send_attemps',
                'ordering': ['status'],
            },
        ),
    ]
