# Generated by Django 5.2.3 on 2025-07-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0005_sendattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendattempt',
            options={'ordering': ['status'], 'verbose_name': 'attempt', 'verbose_name_plural': 'attempts'},
        ),
        migrations.RenameField(
            model_name='sendattempt',
            old_name='attemp_datetime',
            new_name='attempt_datetime',
        ),
    ]
